name: Deploy Live Docker Image

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}

    steps:
      - name: Build and push the Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: share.cny.sh-v8
          tags: latest
          registry: ghcr.io
          dockerfile: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
