name: Deploy Live Docker Image

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build and push the Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: share-cny-sh
          tags: latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
