name: Deploy Live Docker Image

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and push the Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: share-cny-sh
          tags: latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
